/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
          "on-surface": "#fdfbfe",
          "surface-variant": "#242629",
          "on-secondary": "#5a5300",
          "surface-dim": "#0d0e10",
          "surface-bright": "#2b2c2f",
          "error-dim": "#d53d18",
          "on-secondary-fixed-variant": "#645d00",
          "on-primary-fixed-variant": "#596700",
          "secondary-fixed": "#f4e650",
          "outline": "#757578",
          "inverse-primary": "#586500",
          "secondary-fixed-dim": "#e5d843",
          "background": "#0d0e10",
          "secondary-container": "#676000",
          "on-tertiary-fixed-variant": "#675400",
          "on-primary-fixed": "#3f4900",
          "surface-container-high": "#1e2022",
          "on-primary-container": "#505d00",
          "on-error-container": "#ffd2c8",
          "on-tertiary": "#665300",
          "on-background": "#fdfbfe",
          "inverse-surface": "#faf9fb",
          "on-primary": "#586500",
          "on-secondary-container": "#fff8d5",
          "surface-container": "#181a1c",
          "tertiary-fixed-dim": "#eec930",
          "on-error": "#450900",
          "surface-container-low": "#121316",
          "surface": "#0d0e10",
          "surface-container-lowest": "#000000",
          "primary-fixed": "#daf900",
          "primary-container": "#daf900",
          "on-secondary-fixed": "#464000",
          "tertiary-fixed": "#fdd73e",
          "on-surface-variant": "#ababad",
          "primary-fixed-dim": "#cdea00",
          "on-tertiary-fixed": "#463900",
          "outline-variant": "#47484a",
          "inverse-on-surface": "#555557",
          "tertiary-dim": "#eec930",
          "surface-tint": "#f6ffc0",
          "secondary": "#f4e650",
          "primary": "#f6ffc0",
          "primary-dim": "#d0ed00",
          "tertiary-container": "#fdd73e",
          "tertiary": "#ffe798",
          "secondary-dim": "#e5d843",
          "error": "#ff7351",
          "error-container": "#b92902",
          "surface-container-highest": "#242629",
          "on-tertiary-container": "#5c4b00"
      },
      fontFamily: {
          "headline": ["Lexend"],
          "body": ["Lexend"],
          "label": ["Lexend"],
          "lexend": ["Lexend"],
          "lexendBold": ["LexendBold"],
          "lexendExtraBold": ["LexendExtraBold"],
          "lexendBlack": ["LexendBlack"]
      },
    },
  },
  plugins: [],
}
